name: Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement"]
body:
  - type: checkboxes
    id: cloud-suitable
    attributes:
      label: Suitable for cloud AI agent
      description: This issue has enough context for an AI agent to complete the task end-to-end without user input
      options:
        - label: "Cloud AI agent suitable"

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm always frustrated when...
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How do you envision this working?
      placeholder: Describe your ideal solution...
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or features you've considered
      placeholder: I've also thought about...
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or examples
    validations:
      required: false
